### ISSUE TITLE
Does this work in the Access Control role filters?

### ISSUE THREAD

**Issue by petteremil** [u12206050/directus-extension-filters-interface#2]
Hello, I was just wondering if this should work in the access control area as well? 😊 I tried using $CURRENT_ITEM.id, but it didn't seem to save the parameter, so just wondering if I'm doing something wrong, or trying to use it somewhere it shouldn't work? 🤷‍♂️

**Comment by petteremil** [comment]
Just to add an image of how I'm trying to use it 🤸

![image](https://github.com/u12206050/directus-extension-filters-interface/assets/59834762/8a6aa174-8577-4c37-973a-5e1b50439936)

**Comment by u12206050** [comment]
Unfortunately it doesn't change the way Directus applies its own filters such as the ones you have here for permissions. It is for use as a custom field that you yourself use to evaluate using the https://github.com/u12206050/rule-filter-validator
